events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # Automatic HTTP to HTTPS redirection
    server {
        listen 80;
        server_name localhost;
        return 301 https://$host$request_uri;
    }

    # Main HTTPS Gateway Routing Rules
    server {
        listen 443 ssl;
        server_name localhost;

        # Reading corporate certificates out of the mounted secure folder
        ssl_certificate /etc/nginx/ssl/fullchain.pem;
        ssl_certificate_key /etc/nginx/ssl/privkey.pem;

        # 1. FastAPI Custom Dashboards
        location / {
            proxy_pass http://pfe_ai_engine:5000;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # 2. Zabbix Web Interface
        location /zabbix/ {
            proxy_pass http://pfe_zabbix-web:8080/;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # 3. Grafana Analytics Views
        location /grafana/ {
            proxy_pass http://pfe_grafana:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto $scheme;
            
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}