LogFile=C:\zabbix_agentd.log
Server=192.168.0.153
ServerActive=192.168.0.153
Hostname=louay-pc
TLSConnect=psk
TLSAccept=psk
TLSPSKIdentity=AgentID
TLSPSKFile=C:\Users\lenovo\PFE_AI_Audit_AmenBank\zabbix\ssl\agent.psk