LogFile=C:\zabbix_agentd.log
Server=192.168.0.48
ServerActive=192.168.0.48
Hostname=louay-pc
TLSConnect=psk
TLSAccept=psk
TLSPSKIdentity=AgentID
# Use the FULL Windows path to your PSK file
TLSPSKFile=C:\Users\lenovo\PFE_AI_Audit_AmenBank\zabbix\ssl\agent.psk
