Server=0.0.0.0
ServerActive=127.0.0.1
Hostname=louay-pc
TLSConnect=psk
TLSAccept=psk
TLSPSKIdentity=AgentID
TLSPSKFile=C:\Users\lenovo\NEXUS\zabbix\ssl\agent.psk
LogFile=C:\Users\lenovo\NEXUS\zabbix-agent\zabbix_agentd.log